/* SPDX-License-Identifier: GPL-2.0 */


#ifndef _FIRMWARE_XLNX_VERSAL_ERROR_EVENTS_H_
#define _FIRMWARE_XLNX_VERSAL_ERROR_EVENTS_H_


#define VERSAL_EVENT_ERROR_PMC_ERR1	(0x28100000U)
#define VERSAL_EVENT_ERROR_PMC_ERR2	(0x28104000U)
#define VERSAL_EVENT_ERROR_PSM_ERR1	(0x28108000U)
#define VERSAL_EVENT_ERROR_PSM_ERR2	(0x2810C000U)
#define VERSAL_EVENT_ERROR_SW_ERR	(0x28110000U)




#define XPM_VERSAL_EVENT_ERROR_MASK_BOOT_CR		BIT(0)


#define XPM_VERSAL_EVENT_ERROR_MASK_BOOT_NCR		BIT(1)


#define XPM_VERSAL_EVENT_ERROR_MASK_FW_CR		BIT(2)


#define XPM_VERSAL_EVENT_ERROR_MASK_FW_NCR		BIT(3)


#define XPM_VERSAL_EVENT_ERROR_MASK_GSW_CR		BIT(4)


#define XPM_VERSAL_EVENT_ERROR_MASK_GSW_NCR		BIT(5)


#define XPM_VERSAL_EVENT_ERROR_MASK_CFU		BIT(6)


#define XPM_VERSAL_EVENT_ERROR_MASK_CFRAME		BIT(7)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMC_PSM_CR		BIT(8)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMC_PSM_NCR	BIT(9)


#define XPM_VERSAL_EVENT_ERROR_MASK_DDRMB_CR		BIT(10)


#define XPM_VERSAL_EVENT_ERROR_MASK_DDRMB_NCR		BIT(11)


#define XPM_VERSAL_EVENT_ERROR_MASK_NOCTYPE1_CR	BIT(12)


#define XPM_VERSAL_EVENT_ERROR_MASK_NOCTYPE1_NCR	BIT(13)


#define XPM_VERSAL_EVENT_ERROR_MASK_NOCUSER		BIT(14)


#define XPM_VERSAL_EVENT_ERROR_MASK_MMCM		BIT(15)


#define XPM_VERSAL_EVENT_ERROR_MASK_AIE_CR		BIT(16)


#define XPM_VERSAL_EVENT_ERROR_MASK_AIE_NCR		BIT(17)


#define XPM_VERSAL_EVENT_ERROR_MASK_DDRMC_CR		BIT(18)


#define XPM_VERSAL_EVENT_ERROR_MASK_DDRMC_NCR		BIT(19)


#define XPM_VERSAL_EVENT_ERROR_MASK_GT_CR		BIT(20)


#define XPM_VERSAL_EVENT_ERROR_MASK_GT_NCR		BIT(21)


#define XPM_VERSAL_EVENT_ERROR_MASK_PLSMON_CR		BIT(22)


#define XPM_VERSAL_EVENT_ERROR_MASK_PLSMON_NCR		BIT(23)


#define XPM_VERSAL_EVENT_ERROR_MASK_PL0		BIT(24)


#define XPM_VERSAL_EVENT_ERROR_MASK_PL1		BIT(25)


#define XPM_VERSAL_EVENT_ERROR_MASK_PL2		BIT(26)


#define XPM_VERSAL_EVENT_ERROR_MASK_PL3		BIT(27)


#define XPM_VERSAL_EVENT_ERROR_MASK_NPIROOT		BIT(28)


#define XPM_VERSAL_EVENT_ERROR_MASK_SSIT3		BIT(29)


#define XPM_VERSAL_EVENT_ERROR_MASK_SSIT4		BIT(30)


#define XPM_VERSAL_EVENT_ERROR_MASK_SSIT5		BIT(31)




#define XPM_VERSAL_EVENT_ERROR_MASK_PMCAPB		BIT(0)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCROM		BIT(1)


#define XPM_VERSAL_EVENT_ERROR_MASK_MB_FATAL0		BIT(2)


#define XPM_VERSAL_EVENT_ERROR_MASK_MB_FATAL1		BIT(3)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCPAR		BIT(4)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMC_CR		BIT(5)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMC_NCR		BIT(6)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON0		BIT(7)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON1		BIT(8)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON2		BIT(9)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON3		BIT(10)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON4		BIT(11)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON8		BIT(15)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCSMON9		BIT(16)


#define XPM_VERSAL_EVENT_ERROR_MASK_CFI		BIT(17)


#define XPM_VERSAL_EVENT_ERROR_MASK_SEUCRC		BIT(18)


#define XPM_VERSAL_EVENT_ERROR_MASK_SEUECC		BIT(19)


#define XPM_VERSAL_EVENT_ERROR_MASK_RTCALARM		BIT(22)


#define XPM_VERSAL_EVENT_ERROR_MASK_NPLL		BIT(23)


#define XPM_VERSAL_EVENT_ERROR_MASK_PPLL		BIT(24)


#define XPM_VERSAL_EVENT_ERROR_MASK_CLKMON		BIT(25)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCTO		BIT(26)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCXMPU		BIT(27)


#define XPM_VERSAL_EVENT_ERROR_MASK_PMCXPPU		BIT(28)


#define XPM_VERSAL_EVENT_ERROR_MASK_SSIT0		BIT(29)


#define XPM_VERSAL_EVENT_ERROR_MASK_SSIT1		BIT(30)


#define XPM_VERSAL_EVENT_ERROR_MASK_SSIT2		BIT(31)




#define XPM_VERSAL_EVENT_ERROR_MASK_PS_SW_CR		BIT(0)


#define XPM_VERSAL_EVENT_ERROR_MASK_PS_SW_NCR		BIT(1)


#define XPM_VERSAL_EVENT_ERROR_MASK_PSM_B_CR		BIT(2)


#define XPM_VERSAL_EVENT_ERROR_MASK_PSM_B_NCR		BIT(3)


#define XPM_VERSAL_EVENT_ERROR_MASK_MB_FATAL		BIT(4)


#define XPM_VERSAL_EVENT_ERROR_MASK_PSM_CR		BIT(5)


#define XPM_VERSAL_EVENT_ERROR_MASK_PSM_NCR		BIT(6)


#define XPM_VERSAL_EVENT_ERROR_MASK_OCM_ECC		BIT(7)


#define XPM_VERSAL_EVENT_ERROR_MASK_L2_ECC		BIT(8)


#define XPM_VERSAL_EVENT_ERROR_MASK_RPU_ECC		BIT(9)


#define XPM_VERSAL_EVENT_ERROR_MASK_RPU_LS		BIT(10)


#define XPM_VERSAL_EVENT_ERROR_MASK_RPU_CCF		BIT(11)


#define XPM_VERSAL_EVENT_ERROR_MASK_GIC_AXI		BIT(12)


#define XPM_VERSAL_EVENT_ERROR_MASK_GIC_ECC		BIT(13)


#define XPM_VERSAL_EVENT_ERROR_MASK_APLL_LOCK		BIT(14)


#define XPM_VERSAL_EVENT_ERROR_MASK_RPLL_LOCK		BIT(15)


#define XPM_VERSAL_EVENT_ERROR_MASK_CPM_CR		BIT(16)


#define XPM_VERSAL_EVENT_ERROR_MASK_CPM_NCR		BIT(17)


#define XPM_VERSAL_EVENT_ERROR_MASK_LPD_APB		BIT(18)


#define XPM_VERSAL_EVENT_ERROR_MASK_FPD_APB		BIT(19)


#define XPM_VERSAL_EVENT_ERROR_MASK_LPD_PAR		BIT(20)


#define XPM_VERSAL_EVENT_ERROR_MASK_FPD_PAR		BIT(21)


#define XPM_VERSAL_EVENT_ERROR_MASK_IOU_PAR		BIT(22)


#define XPM_VERSAL_EVENT_ERROR_MASK_PSM_PAR		BIT(23)


#define XPM_VERSAL_EVENT_ERROR_MASK_LPD_TO		BIT(24)


#define XPM_VERSAL_EVENT_ERROR_MASK_FPD_TO		BIT(25)


#define XPM_VERSAL_EVENT_ERROR_MASK_PSM_TO		BIT(26)


#define XPM_VERSAL_EVENT_ERROR_MASK_XRAM_CR		BIT(27)


#define XPM_VERSAL_EVENT_ERROR_MASK_XRAM_NCR		BIT(28)




#define XPM_VERSAL_EVENT_ERROR_MASK_LPD_SWDT		BIT(0)


#define XPM_VERSAL_EVENT_ERROR_MASK_FPD_SWDT		BIT(1)


#define XPM_VERSAL_EVENT_ERROR_MASK_LPD_XMPU		BIT(18)


#define XPM_VERSAL_EVENT_ERROR_MASK_LPD_XPPU		BIT(19)


#define XPM_VERSAL_EVENT_ERROR_MASK_FPD_XMPU		BIT(20)




#define XPM_VERSAL_EVENT_ERROR_MASK_HB_MON_0		BIT(0)


#define XPM_VERSAL_EVENT_ERROR_MASK_HB_MON_1		BIT(1)


#define XPM_VERSAL_EVENT_ERROR_MASK_HB_MON_2		BIT(2)


#define XPM_VERSAL_EVENT_ERROR_MASK_HB_MON_3		BIT(3)


#define XPM_VERSAL_EVENT_ERROR_MASK_XSEM_CRAM_CE_5		BIT(5)


#define XPM_VERSAL_EVENT_ERROR_MASK_XSEM_CRAM_UE_6		BIT(6)


#define XPM_VERSAL_EVENT_ERROR_MASK_XSEM_NPI_UE_7		BIT(7)

#endif 
