/* SPDX-License-Identifier: GPL-2.0 */


#ifndef _FIRMWARE_XLNX_VERSAL_NET_ERROR_EVENTS_H_
#define _FIRMWARE_XLNX_VERSAL_NET_ERROR_EVENTS_H_


#define VERSAL_NET_EVENT_ERROR_PMC_ERR1	(0x28100000U)
#define VERSAL_NET_EVENT_ERROR_PMC_ERR2	(0x28104000U)
#define VERSAL_NET_EVENT_ERROR_PMC_ERR3	(0x28108000U)
#define VERSAL_NET_EVENT_ERROR_PSM_ERR1	(0x2810C000U)
#define VERSAL_NET_EVENT_ERROR_PSM_ERR2	(0x28110000U)
#define VERSAL_NET_EVENT_ERROR_PSM_ERR3	(0x28114000U)
#define VERSAL_NET_EVENT_ERROR_PSM_ERR4	(0x28118000U)
#define VERSAL_NET_EVENT_ERROR_SW_ERR	(0x2811C000U)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_BOOT_CR		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_BOOT_NCR		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FW_CR		BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FW_NCR		BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_GSW_CR		BIT(4)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_GSW_NCR		BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CFU		BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CFRAME		BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMC_PSM_CR		BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMC_PSM_NCR	BIT(9)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DDRMB_CR		BIT(10)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DDRMB_NCR		BIT(11)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NOCTYPE1_CR	BIT(12)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NOCTYPE1_NCR	BIT(13)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NOCUSER		BIT(14)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MMCM		BIT(15)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_AIE_CR		BIT(16)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_AIE_NCR		BIT(17)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DDRMC_CR		BIT(18)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DDRMC_NCR		BIT(19)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_GT_CR		BIT(20)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_GT_NCR		BIT(21)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PLSMON_CR		BIT(22)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PLSMON_NCR		BIT(23)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PL0		BIT(24)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PL1		BIT(25)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PL2		BIT(26)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PL3		BIT(27)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NPIROOT		BIT(28)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SSIT3		BIT(29)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SSIT4		BIT(30)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SSIT5		BIT(31)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCAPB		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCROM		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MB_FATAL0		BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MB_FATAL1		BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMC_CR		BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMC_NCR		BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON0		BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON1		BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON2		BIT(9)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON3		BIT(10)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON4		BIT(11)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON8		BIT(15)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMCSMON9		BIT(16)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CFI		BIT(17)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SEUCRC		BIT(18)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SEUECC		BIT(19)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PMX_WWDT		BIT(20)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_RTCALARM		BIT(22)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NPLL		BIT(23)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PPLL		BIT(24)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CLKMON		BIT(25)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_PMX_CORR_ERR	BIT(27)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_PMX_UNCORR_ERR	BIT(28)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SSIT0		BIT(29)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SSIT1		BIT(30)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_SSIT2		BIT(31)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_IOU_CR		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_IOU_NCR		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DFX_UXPT_ACT	BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DICE_CDI_PAR	BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DEVIK_PRIV		BIT(4)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NXTSW_CDI_PAR	BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DEVAK_PRIV		BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DME_PUB_X		BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DME_PUB_Y		BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DEVAK_PUB_X	BIT(9)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DEVAK_PUB_Y	BIT(10)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DEVIK_PUB_X	BIT(11)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_DEVIK_PUB_Y	BIT(12)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PCR_PAR		BIT(13)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PS_SW_CR		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PS_SW_NCR		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSM_B_CR		BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSM_B_NCR		BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MB_FATAL		BIT(4)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSM_CR		BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSM_NCR		BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSMX_CHK		BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APLL1_LOCK		BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APLL2_LOCK		BIT(9)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_RPLL_LOCK		BIT(10)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FLXPLL_LOCK	BIT(11)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_PSM_CR		BIT(12)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_PSM_NCR	BIT(13)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_USB2		BIT(14)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPX_UXPT_ACT	BIT(15)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_LPD_CR		BIT(17)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_LPD_NCR	BIT(18)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_OCM_CR		BIT(19)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_OCM_NCR	BIT(20)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_FPD_CR		BIT(21)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_FPD_NCR	BIT(22)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_IOU_CR		BIT(23)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_INT_IOU_NCR	BIT(24)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_RPUA_LOCKSTEP	BIT(25)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_RPUB_LOCKSTEP	BIT(26)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APU_GIC_AXI	BIT(27)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APU_GIC_ECC	BIT(28)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CPM_CR		BIT(29)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CPM_NCR		BIT(30)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_CPI		BIT(31)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPD_WDT0		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPD_WDT1		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPD_WDT2		BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPD_WDT3		BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MEM_SPLITTER0	BIT(4)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_AXI_PAR_SPLITTER0	BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MEM_SPLITTER1	BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_AXI_PAR_SPLITTER1	BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MEM_SPLITTER2	BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_AXI_PAR_SPLITTER2	BIT(9)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_MEM_SPLITTER3	BIT(10)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_AXI_PAR_SPLITTER3	BIT(11)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APU_CLUSTER0	BIT(12)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APU_CLUSTER1	BIT(13)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APU_CLUSTER2	BIT(14)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_APU_CLUSTER3	BIT(15)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPD_WWDT0		BIT(16)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPD_WWDT1		BIT(17)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_ADMA_LOCKSTEP	BIT(18)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_IPI		BIT(19)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_OCM_BANK0_CR	BIT(20)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_OCM_BANK1_CR	BIT(21)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_OCM_BANK0_NCR	BIT(22)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_OCM_BANK1_NCR	BIT(23)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPXAFIFS_CR	BIT(24)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPXAFIFS_NCR	BIT(25)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPX_GLITCH_DETECT0	BIT(26)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPX_GLITCH_DETECT1	BIT(27)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FWALL_WR_NOC_NMU	BIT(28)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FWALL_RD_NOC_NMU	BIT(29)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FWALL_NOC_NSU	BIT(30)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B18_R52_A0		BIT(31)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B18_R52_A1		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B18_R52_B0		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B18_R52_B1		BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_A0_CR		BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_A0_TFATAL	BIT(4)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_A0_TIMEOUT	BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B24_B20_RPUA0	BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B25_RPUA0		BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_A1_CR		BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_A1_TFATAL	BIT(9)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_A1_TIMEOUT	BIT(10)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B24_B20_RPUA1	BIT(11)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B25_RPUA1		BIT(12)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_B0_CR		BIT(13)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_B0_TFATAL	BIT(14)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_B0_TIMEOUT	BIT(15)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B24_B20_RPUB0	BIT(16)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B25_RPUB0		BIT(17)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_B1_CR		BIT(18)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_B1_TFATAL	BIT(19)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_R52_B1_TIMEOUT	BIT(20)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B24_B20_RPUB1	BIT(21)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_B25_RPUB1		BIT(22)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PCIL_RPU		BIT(24)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPXAFIFS_CR	BIT(25)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPXAFIFS_NCR	BIT(26)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSX_CMN_1		BIT(27)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSX_CMN_2		BIT(28)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSX_CMN_3		BIT(29)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_PSX_CML		BIT(30)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPD_INT_WRAP	BIT(31)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FPD_RST_MON	BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_LPD_RST_CLK_MON	BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_FATAL_AFI_FM	BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NFATAL_AFI_FM_LPX	BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NFATAL_AFI_FM0_FPX	BIT(4)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NFATAL_AFI_FM1_FPX	BIT(5)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NFATAL_AFI_FM2_FPX	BIT(6)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_NFATAL_AFI_FM3_FPX	BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_RPU_CLUSTERA	BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_RPU_CLUSTERB	BIT(9)




#define XPM_VERSAL_NET_EVENT_ERROR_MASK_HB_MON_0		BIT(0)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_HB_MON_1		BIT(1)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_HB_MON_2		BIT(2)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_HB_MON_3		BIT(3)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_XSEM_CRAM_CE		BIT(7)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_XSEM_CRAM_UE		BIT(8)


#define XPM_VERSAL_NET_EVENT_ERROR_MASK_XSEM_NPI_UE		BIT(9)

#endif 
