/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */


#ifndef __UAPI_XILINX_V4L2_CONTROLS_H__
#define __UAPI_XILINX_V4L2_CONTROLS_H__

#include <linux/v4l2-controls.h>

#define V4L2_CID_XILINX_OFFSET	0xc000
#define V4L2_CID_XILINX_BASE	(V4L2_CID_USER_BASE + V4L2_CID_XILINX_OFFSET)





#define V4L2_CID_XILINX_TPG			(V4L2_CID_USER_BASE + 0xc000)


#define V4L2_CID_XILINX_TPG_CROSS_HAIRS		(V4L2_CID_XILINX_TPG + 1)

#define V4L2_CID_XILINX_TPG_MOVING_BOX		(V4L2_CID_XILINX_TPG + 2)

#define V4L2_CID_XILINX_TPG_COLOR_MASK		(V4L2_CID_XILINX_TPG + 3)

#define V4L2_CID_XILINX_TPG_STUCK_PIXEL		(V4L2_CID_XILINX_TPG + 4)

#define V4L2_CID_XILINX_TPG_NOISE		(V4L2_CID_XILINX_TPG + 5)

#define V4L2_CID_XILINX_TPG_MOTION		(V4L2_CID_XILINX_TPG + 6)

#define V4L2_CID_XILINX_TPG_MOTION_SPEED	(V4L2_CID_XILINX_TPG + 7)

#define V4L2_CID_XILINX_TPG_CROSS_HAIR_ROW	(V4L2_CID_XILINX_TPG + 8)

#define V4L2_CID_XILINX_TPG_CROSS_HAIR_COLUMN	(V4L2_CID_XILINX_TPG + 9)

#define V4L2_CID_XILINX_TPG_ZPLATE_HOR_START	(V4L2_CID_XILINX_TPG + 10)

#define V4L2_CID_XILINX_TPG_ZPLATE_HOR_SPEED	(V4L2_CID_XILINX_TPG + 11)

#define V4L2_CID_XILINX_TPG_ZPLATE_VER_START	(V4L2_CID_XILINX_TPG + 12)

#define V4L2_CID_XILINX_TPG_ZPLATE_VER_SPEED	(V4L2_CID_XILINX_TPG + 13)

#define V4L2_CID_XILINX_TPG_BOX_SIZE		(V4L2_CID_XILINX_TPG + 14)

#define V4L2_CID_XILINX_TPG_BOX_COLOR		(V4L2_CID_XILINX_TPG + 15)

#define V4L2_CID_XILINX_TPG_STUCK_PIXEL_THRESH	(V4L2_CID_XILINX_TPG + 16)

#define V4L2_CID_XILINX_TPG_NOISE_GAIN		(V4L2_CID_XILINX_TPG + 17)

#define V4L2_CID_XILINX_TPG_HLS_FG_PATTERN     (V4L2_CID_XILINX_TPG + 18)



#define V4L2_CID_XILINX_CRESAMPLE		(V4L2_CID_USER_BASE + 0xc020)


#define V4L2_CID_XILINX_CRESAMPLE_FIELD_PARITY	(V4L2_CID_XILINX_CRESAMPLE + 1)

#define V4L2_CID_XILINX_CRESAMPLE_CHROMA_PARITY	(V4L2_CID_XILINX_CRESAMPLE + 2)



#define V4L2_CID_XILINX_RGB2YUV			(V4L2_CID_USER_BASE + 0xc040)


#define V4L2_CID_XILINX_RGB2YUV_YMAX		(V4L2_CID_XILINX_RGB2YUV + 1)

#define V4L2_CID_XILINX_RGB2YUV_YMIN		(V4L2_CID_XILINX_RGB2YUV + 2)

#define V4L2_CID_XILINX_RGB2YUV_CBMAX		(V4L2_CID_XILINX_RGB2YUV + 3)

#define V4L2_CID_XILINX_RGB2YUV_CBMIN		(V4L2_CID_XILINX_RGB2YUV + 4)

#define V4L2_CID_XILINX_RGB2YUV_CRMAX		(V4L2_CID_XILINX_RGB2YUV + 5)

#define V4L2_CID_XILINX_RGB2YUV_CRMIN		(V4L2_CID_XILINX_RGB2YUV + 6)

#define V4L2_CID_XILINX_RGB2YUV_YOFFSET		(V4L2_CID_XILINX_RGB2YUV + 7)

#define V4L2_CID_XILINX_RGB2YUV_CBOFFSET	(V4L2_CID_XILINX_RGB2YUV + 8)

#define V4L2_CID_XILINX_RGB2YUV_CROFFSET	(V4L2_CID_XILINX_RGB2YUV + 9)




#define V4L2_CID_XILINX_RGB2YUV_ACOEF		(V4L2_CID_XILINX_RGB2YUV + 10)

#define V4L2_CID_XILINX_RGB2YUV_BCOEF		(V4L2_CID_XILINX_RGB2YUV + 11)

#define V4L2_CID_XILINX_RGB2YUV_CCOEF		(V4L2_CID_XILINX_RGB2YUV + 12)

#define V4L2_CID_XILINX_RGB2YUV_DCOEF		(V4L2_CID_XILINX_RGB2YUV + 13)



#define V4L2_CID_XILINX_HLS			(V4L2_CID_USER_BASE + 0xc060)


#define V4L2_CID_XILINX_HLS_MODEL		(V4L2_CID_XILINX_HLS + 1)




#define V4L2_CID_XILINX_GAMMA_CORR		(V4L2_CID_USER_BASE + 0xc0c0)

#define V4L2_CID_XILINX_GAMMA_CORR_RED_GAMMA	(V4L2_CID_XILINX_GAMMA_CORR + 1)

#define V4L2_CID_XILINX_GAMMA_CORR_BLUE_GAMMA	(V4L2_CID_XILINX_GAMMA_CORR + 2)

#define V4L2_CID_XILINX_GAMMA_CORR_GREEN_GAMMA	(V4L2_CID_XILINX_GAMMA_CORR + 3)




#define V4L2_CID_XILINX_CSC			(V4L2_CID_USER_BASE + 0xc0a0)

#define V4L2_CID_XILINX_CSC_BRIGHTNESS		(V4L2_CID_XILINX_CSC + 1)

#define V4L2_CID_XILINX_CSC_CONTRAST		(V4L2_CID_XILINX_CSC + 2)

#define V4L2_CID_XILINX_CSC_RED_GAIN		(V4L2_CID_XILINX_CSC + 3)

#define V4L2_CID_XILINX_CSC_GREEN_GAIN		(V4L2_CID_XILINX_CSC + 4)

#define V4L2_CID_XILINX_CSC_BLUE_GAIN		(V4L2_CID_XILINX_CSC + 5)




#define V4L2_CID_XILINX_SDIRX			(V4L2_CID_USER_BASE + 0xc100)


#define V4L2_CID_XILINX_SDIRX_FRAMER		(V4L2_CID_XILINX_SDIRX + 1)

#define V4L2_CID_XILINX_SDIRX_VIDLOCK_WINDOW	(V4L2_CID_XILINX_SDIRX + 2)

#define V4L2_CID_XILINX_SDIRX_EDH_ERRCNT_ENABLE	(V4L2_CID_XILINX_SDIRX + 3)

#define V4L2_CID_XILINX_SDIRX_SEARCH_MODES	(V4L2_CID_XILINX_SDIRX + 4)

#define V4L2_CID_XILINX_SDIRX_MODE_DETECT	(V4L2_CID_XILINX_SDIRX + 5)

#define V4L2_CID_XILINX_SDIRX_CRC		(V4L2_CID_XILINX_SDIRX + 6)

#define V4L2_CID_XILINX_SDIRX_EDH_ERRCNT	(V4L2_CID_XILINX_SDIRX + 7)

#define V4L2_CID_XILINX_SDIRX_EDH_STATUS	(V4L2_CID_XILINX_SDIRX + 8)

#define V4L2_CID_XILINX_SDIRX_TS_IS_INTERLACED	(V4L2_CID_XILINX_SDIRX + 9)

#define V4L2_CID_XILINX_SDIRX_ACTIVE_STREAMS	(V4L2_CID_XILINX_SDIRX + 10)

#define V4L2_CID_XILINX_SDIRX_IS_3GB		(V4L2_CID_XILINX_SDIRX + 11)




#define V4L2_CID_XILINX_VIP			(V4L2_CID_USER_BASE + 0xc120)


#define V4L2_CID_XILINX_LOW_LATENCY		(V4L2_CID_XILINX_VIP + 1)


#define XVIP_LOW_LATENCY_ENABLE		BIT(1)
#define XVIP_LOW_LATENCY_DISABLE	BIT(2)


#define XVIP_START_DMA			BIT(3)




#define V4L2_CID_XILINX_SCD			(V4L2_CID_USER_BASE + 0xc140)


#define V4L2_CID_XILINX_SCD_THRESHOLD		(V4L2_CID_XILINX_SCD + 1)




#define V4L2_CID_XILINX_ISP			(V4L2_CID_USER_BASE + 0xc160)

#define V4L2_CID_XILINX_ISP_RED_GAIN		(V4L2_CID_XILINX_ISP + 1)

#define V4L2_CID_XILINX_ISP_BLUE_GAIN		(V4L2_CID_XILINX_ISP + 2)

#define V4L2_CID_XILINX_ISP_AWB			(V4L2_CID_XILINX_ISP + 3)

#define V4L2_CID_XILINX_ISP_THRESHOLD		(V4L2_CID_XILINX_ISP + 4)

#define V4L2_CID_XILINX_ISP_RED_GAMMA		(V4L2_CID_XILINX_ISP + 5)

#define V4L2_CID_XILINX_ISP_GREEN_GAMMA		(V4L2_CID_XILINX_ISP + 6)

#define V4L2_CID_XILINX_ISP_BLUE_GAMMA		(V4L2_CID_XILINX_ISP + 7)

#define V4L2_CID_XILINX_ISP_AEC_EN		(V4L2_CID_XILINX_ISP + 8)

#define V4L2_CID_XILINX_ISP_AEC_THRESHOLD		(V4L2_CID_XILINX_ISP + 9)

#define V4L2_CID_XILINX_ISP_BLC_EN		(V4L2_CID_XILINX_ISP + 10)

#define V4L2_CID_XILINX_ISP_MULTI_FACTOR	(V4L2_CID_XILINX_ISP + 11)

#define V4L2_CID_XILINX_ISP_AWB_EN		(V4L2_CID_XILINX_ISP + 12)

#define V4L2_CID_XILINX_ISP_AWB_THRESHOLD	(V4L2_CID_XILINX_ISP + 13)

#define V4L2_CID_XILINX_ISP_BPC_EN		(V4L2_CID_XILINX_ISP + 14)

#define V4L2_CID_XILINX_ISP_DEGAMMA_EN		(V4L2_CID_XILINX_ISP + 15)

#define V4L2_CID_XILINX_ISP_DEGAMMA_PARAMS		(V4L2_CID_XILINX_ISP + 16)

#define V4L2_CID_XILINX_ISP_RGBIR_EN		(V4L2_CID_XILINX_ISP + 17)

#define V4L2_CID_XILINX_ISP_LSC_EN		(V4L2_CID_XILINX_ISP + 18)

#define V4L2_CID_XILINX_ISP_DEMOSAIC_EN		(V4L2_CID_XILINX_ISP + 39)

#define V4L2_CID_XILINX_ISP_CCM_EN		(V4L2_CID_XILINX_ISP + 20)

#define V4L2_CID_XILINX_ISP_CCM_PARAMS		(V4L2_CID_XILINX_ISP + 21)

#define V4L2_CID_XILINX_ISP_GAIN_EN		(V4L2_CID_XILINX_ISP + 22)

#define V4L2_CID_XILINX_ISP_GAIN_CONTROL_RED_GAIN		(V4L2_CID_XILINX_ISP + 23)

#define V4L2_CID_XILINX_ISP_GAIN_CONTROL_BLUE_GAIN		(V4L2_CID_XILINX_ISP + 24)

#define V4L2_CID_XILINX_ISP_GAIN_CONTROL_GREEN_GAIN		(V4L2_CID_XILINX_ISP + 52)

#define V4L2_CID_XILINX_ISP_LUMA_GAIN		(V4L2_CID_XILINX_ISP + 25)

#define V4L2_CID_XILINX_ISP_GAMMA_EN		(V4L2_CID_XILINX_ISP + 26)

#define V4L2_CID_XILINX_ISP_HDR_EN			(V4L2_CID_XILINX_ISP + 27)

#define V4L2_CID_XILINX_ISP_DECOMPAND_PARAMS		(V4L2_CID_XILINX_ISP + 28)

#define V4L2_CID_XILINX_ISP_ALPHA		(V4L2_CID_XILINX_ISP + 29)

#define V4L2_CID_XILINX_ISP_OPTICAL_BLACK_VALUE	(V4L2_CID_XILINX_ISP + 30)

#define V4L2_CID_XILINX_ISP_INTERSEC		(V4L2_CID_XILINX_ISP + 31)

#define V4L2_CID_XILINX_ISP_RHO			(V4L2_CID_XILINX_ISP + 32)

#define V4L2_CID_XILINX_ISP_TM_EN		(V4L2_CID_XILINX_ISP + 33)

#define V4L2_CID_XILINX_ISP_GTM_C1		(V4L2_CID_XILINX_ISP + 34)

#define V4L2_CID_XILINX_ISP_GTM_C2		(V4L2_CID_XILINX_ISP + 35)

#define V4L2_CID_XILINX_ISP_BLOCK_ROWS		(V4L2_CID_XILINX_ISP + 36)

#define V4L2_CID_XILINX_ISP_BLOCK_COLS		(V4L2_CID_XILINX_ISP + 37)

#define V4L2_CID_XILINX_ISP_3DLUT_EN		(V4L2_CID_XILINX_ISP + 38)

#define V4L2_CID_XILINX_ISP_3DLUT_DIM		(V4L2_CID_XILINX_ISP + 40)

#define V4L2_CID_XILINX_ISP_CSC_EN		(V4L2_CID_XILINX_ISP + 41)

#define V4L2_CID_XILINX_ISP_BAYER_STATS_EN		(V4L2_CID_XILINX_ISP + 42)

#define V4L2_CID_XILINX_ISP_LUMA_STATS_EN		(V4L2_CID_XILINX_ISP + 43)

#define V4L2_CID_XILINX_ISP_RGB_STATS_EN		(V4L2_CID_XILINX_ISP + 44)

#define V4L2_CID_XILINX_ISP_CLAHE_EN		(V4L2_CID_XILINX_ISP + 45)

#define V4L2_CID_XILINX_ISP_CLIP		(V4L2_CID_XILINX_ISP + 46)

#define V4L2_CID_XILINX_ISP_TILESY		(V4L2_CID_XILINX_ISP + 47)

#define V4L2_CID_XILINX_ISP_TILESX		(V4L2_CID_XILINX_ISP + 48)

#define V4L2_CID_XILINX_ISP_MEDIAN_EN		(V4L2_CID_XILINX_ISP + 49)

#define V4L2_CID_XILINX_ISP_RESIZE_EN		(V4L2_CID_XILINX_ISP + 50)

#define V4L2_CID_XILINX_ISP_EN			(V4L2_CID_XILINX_ISP + 51)

#endif 
